### PR TITLE
CRISTAL-178: Integrate tiptap

### PR DESCRIPTION
**Pull request by manuelleduc**
# Jira URL

https://jira.xwiki.org/browse/CRISTAL-178

# Changes

## Description

* Replace all experimental editors with tiptap (see https://forum.xwiki.org/t/choice-of-editor/14414/)

## TODO

- [x] Improve the quick action text
- [ ] improve the appearance of the quick action and select action (cc @tkrieck, I could use your help for some brainstorming)
- [x] offer more actions that might be easy to integrate (e.g., code block, tables, line through, underline), and document those that have hidden difficulty, to integrate them separately
  - [x] table: currently no style is provided for tables, meaning that the tables can be viewed and editor, but the cells have no visible borders (cc @tkrieck, I'll provide a minimalistic style but feel free to improve)
  - [x] blockquote: same as table, no specific visual distinction (same as non-styled text).
  - [x] warning/info/etc message: we need to clean up macro support before introducing them back
- [x] propose keyboard actions on the select menu
- [x] display icons and alt texts
- [x] do a quick a11y and usability study 

## Clarifications

* Provide a quick action with / on new lines
* Provide a contextual menu based on content selection (only offer actions applicable to the current selection)

# Screenshots & Video

[Screencast from 13-05-2024 10:48:24.webm](https://github.com/xwiki-contrib/cristal/assets/327856/35f995a8-049d-4d28-9568-ae5b2ef02d49)
[Screencast from 13-05-2024 10:48:01.webm](https://github.com/xwiki-contrib/cristal/assets/327856/1c9ee9e6-8dd8-44ed-87c1-a9b4e757f1bc)

# Expected merging strategy

* Prefers squash: Yes

### CODE REVIEW

**Comment by tkrieck** [comment]
>  improve the appearance of the quick action and select action (cc @tkrieck, I could use your help for some brainstorming)

Do you have a screenshot or link that I can work with? I tried running the branch, but the project is not building.

**Comment by manuelleduc** [comment]
> Do you have a screenshot or link that I can work with? I tried running the branch, but the project is not building.

I can provide screenshots, but can you tell me what's failing when you try to build?

**Comment by tkrieck** [comment]
> I can provide screenshots, but can you tell me what's failing when you try to build?

Sure, after your latest changes the message is different.
What I did:
Pulled the changes and ran `pnpm install`
Then `pnpm run start` the build goes on without issues for a while and the error below happens. The same with `pnpm run dev` but the error is quick to appear.


```
> @cristal/editors-tiptap@1.0.0 compile /Users/thiago/Developer/cristal/editors/tiptap
> vue-tsc --project tsconfig.json --noEmit && vite build

src/components/componentsInit.ts(34,11): error TS2345: Argument of type 'typeof UixTiptapEditorProvider' is not assignable to parameter of type 'Newable<VueTemplateProvider>'.
  Construct signature return types 'UixTiptapEditorProvider' and 'VueTemplateProvider' are incompatible.
    The types returned by 'getVueComponent()' are incompatible between these types.
      Type 'import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").Component' is not assignable to type 'import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").Component'.
src/components/uixTiptapEditorProvider.ts(42,3): error TS2416: Property 'getVueComponent' in type 'UixTiptapEditorProvider' is not assignable to the same property in base type 'DefaultVueTemplateProvider'.
  Type '() => import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").Component' is not assignable to type '() => import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").Component'.
    Type 'import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").Component' is not assignable to type 'import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").Component'.
      Type 'ComponentOptions<any, any, any, ComputedOptions, MethodOptions, any, any, any, any>' is not assignable to type 'Component'.
        Type 'ComponentOptions<any, any, any, ComputedOptions, MethodOptions, any, any, any, any>' is not assignable to type 'FunctionalComponent<any, {}, any, {}>'.
          Types of property 'compatConfig' are incompatible.
            Type 'CompatConfig | undefined' is not assignable to type 'CompatConfig | undefined'. Two different types with this name exist, but they are unrelated.
              Type 'CompatConfig' is not assignable to type 'CompatConfig | undefined'.
                Type 'CompatConfig' is not assignable to type 'CompatConfig'. Two different types with this name exist, but they are unrelated.
                  Type 'CompatConfig' is not assignable to type '{ MODE?: 2 | 3 | ((comp: Component<any, any, any, ComputedOptions, MethodOptions, {}, any> | null) => 2 | 3) | undefined; }'.
                    Types of property 'MODE' are incompatible.
                      Type '2 | 3 | ((comp: import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").Component<any, any, any, import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").ComputedOptions, import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/r...' is not assignable to type '2 | 3 | ((comp: import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").Component<any, any, any, import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").Comput...'.
                        Type '(comp: Component<any, any, any, ComputedOptions, MethodOptions, {}, any> | null) => 2 | 3' is not assignable to type '2 | 3 | ((comp: Component<any, any, any, ComputedOptions, MethodOptions, {}, any> | null) => 2 | 3) | undefined'.
                          Type '(comp: import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").Component<any, any, any, import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").ComputedOptions, import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-co...' is not assignable to type '(comp: import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").Component<any, any, any, import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").ComputedOptions...'.
                            Types of parameters 'comp' and 'comp' are incompatible.
                              Type 'import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").Component<any, any, any, import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").ComputedOptions, impor...' is not assignable to type 'import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").Component<any, any, any, import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").ComputedOptions, import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").Me...'.
                                Type 'ComponentOptions<any, any, any, ComputedOptions, MethodOptions, any, any, any, any>' is not assignable to type 'Component<any, any, any, ComputedOptions, MethodOptions, {}, any> | null'.
                                  Type 'ComponentOptions<any, any, any, ComputedOptions, MethodOptions, any, any, any, any>' is not assignable to type 'FunctionalComponent<any, {}, any, {}>'.
                                    Types of property 'compatConfig' are incompatible.
                                      Type 'CompatConfig | undefined' is not assignable to type 'CompatConfig | undefined'. Two different types with this name exist, but they are unrelated.
                                        Type 'CompatConfig' is not assignable to type 'CompatConfig | undefined'.
                                          Type 'CompatConfig' is not assignable to type 'CompatConfig'. Two different types with this name exist, but they are unrelated.
                                            Type 'CompatConfig' is not assignable to type '{ MODE?: 2 | 3 | ((comp: Component<any, any, any, ComputedOptions, MethodOptions, {}, any> | null) => 2 | 3) | undefined; }'.
                                              Types of property 'MODE' are incompatible.
                                                Type '2 | 3 | ((comp: import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").Component<any, any, any, import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").Comput...' is not assignable to type '2 | 3 | ((comp: import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").Component<any, any, any, import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").ComputedOptions, import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/r...'.
                                                  Type '(comp: Component<any, any, any, ComputedOptions, MethodOptions, {}, any> | null) => 2 | 3' is not assignable to type '2 | 3 | ((comp: Component<any, any, any, ComputedOptions, MethodOptions, {}, any> | null) => 2 | 3) | undefined'.
                                                    Type '(comp: import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").Component<any, any, any, import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").ComputedOptions...' is not assignable to type '(comp: import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").Component<any, any, any, import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").ComputedOptions, import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-co...'.
                                                      Types of parameters 'comp' and 'comp' are incompatible.
                                                        Type 'import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").Component<any, any, any, import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").ComputedOptions, import("/Users/thiago/Developer/cristal/node_modules/@vue/runtime-core/dist/runtime-core").Me...' is not assignable to type 'import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").Component<any, any, any, import("/Users/thiago/Developer/cristal/node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core").ComputedOptions, impor...'.
                                                          Type 'ComponentOptions<any, any, any, ComputedOptions, MethodOptions, any, any, any, any>' is not assignable to type 'Component<any, any, any, ComputedOptions, MethodOptions, {}, any> | null'.
                                                            Type 'ComponentOptions<any, any, any, ComputedOptions, MethodOptions, any, any, any, any>' is not assignable to type 'FunctionalComponent<any, {}, any, {}>'.
                                                              Types of property 'compatConfig' are incompatible.
                                                                Type 'CompatConfig | undefined' is not assignable to type 'CompatConfig | undefined'. Two different types with this name exist, but they are unrelated.
                                                                  Type 'CompatConfig' is not assignable to type 'CompatConfig | undefined'.
 ELIFECYCLE  Command failed with exit code 2.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by manuelleduc** [comment]
> > I can provide screenshots, but can you tell me what's failing when you try to build?
> 
> Sure, after your latest changes the message is different. What I did: Pulled the changes and ran `pnpm install` Then `pnpm run start` the build goes on without issues for a while and the error below happens. The same with `pnpm run dev` but the error is quick to appear.
> ```
Can you try running `pnpm exec nx reset` before running dev/start again? To rule out the possibility of a nx cache issue.

**Comment by tkrieck** [comment]
> pnpm exec nx reset

I tried it, same issue =(

**Pull request merged**
